image: maven:3-jdk-11

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl


stages:
    - deploy-staging



staging:
    stage: deploy-staging
    image: ruby:latest
    script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
    only:
        - master
